### ISSUE TITLE
Error when going on "Activity" tag

### ISSUE THREAD

**Issue by watertrainer** [ActivityWatch/aw-webui#298] opened 2021-06-29 20:49 UTC
When going onto Activity watch and trying to view my recent activity, I am getting the following error:
```
TypeError: t is undefined
    datasets TimelineBarChart.vue:99
    Lodash 10
    value TimelineBarChart.vue:99
    value TimelineBarChart.vue:50
    VueJS 4
```
The server log shows the following repeatedly:
```
[WARNING]: Gap was of negative duration but could be safely merged (-329.765s). This message will only show once per batch.  (aw_transform.flood:48)
[WARNING]: Gap was of negative duration and could NOT be safely merged (-383.599s). This warning will only show once per batch.  (aw_transform.flood:56)
```

This has happend to me on multiple days, so its (probably) not an issue with the loaded data.
This has not occured before I updated

**Comment by ErikBjare** [comment] 2021-07-01 12:28
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/612, closing.

**Closed by ErikBjare** 2021-07-01 12:28 UTC
