### ISSUE TITLE
Names of siblings with same class name are updated together in categorization section

### ISSUE THREAD

**Issue by pratham2003** [ActivityWatch/aw-webui#187] opened 2020-04-21 06:15 UTC
A gif illustrating the issue.
![Demo](https://s4.gifyu.com/images/2020-04-21_11-46-41.gif)

It looks related to this part of the code.
https://github.com/ActivityWatch/aw-webui/blob/34511961e36207ce3bdb26ba05613e46fa083950/src/store/modules/settings.js#L68

**Comment by ErikBjare** [comment] 2020-04-21 07:22
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/361

Closing.

**Closed** 2020-04-21 07:22 UTC
Labels: duplicate
