### ISSUE TITLE
Still blank in browsers 

### ISSUE THREAD

**Issue by aquirin** [ActivityWatch/aw-webui#114] opened 2018-10-06 22:25 UTC
Opened again 

Not clear why it should not work in Internet Explorer if for other browser it is working perfectly 

Also who closed it did not see firefox was tested in my original message 

Opening the dashboard in the browser gives a completely blank page.

The port is free, I tried also another port.

Source of the page still show data (<title>ActivityWatch</title>...)

Console show an error:
SyntaxError: missing = in const declaration
(File: /static/js/0.eb46a9d79636be6aeb56.js, in 13590)

API Browser (http://localhost:5600/api/) is working fine

Version:
•activitywatch: v0.8.0b6
•firefox: 47
•internet explorer: 11.2485

**Comment by ErikBjare** [comment] 2018-10-06 22:36
>Not clear why it should not work in Internet Explorer if for other browser it is working perfectly

Because Internet Explorer is a piece of shit. Please do not create new issues instead of reopening ones.

Duplicate of:
 - https://github.com/ActivityWatch/aw-webui/issues/112
 - https://github.com/ActivityWatch/docs/issues/12

**Closed by ErikBjare** 2018-10-06 22:36 UTC
Labels: duplicate, wontfix

**Comment by aquirin** [comment] 2018-10-06 22:55
Who did appointed you as an admin?  

Can someone provide a more professional and less childish answer? 

What about Firefox in my original message?

**Comment by ErikBjare** [comment] 2018-10-06 23:01
@aquirin I am the original creator and main contributor of this entire project and I suggest you stop expressing entitlement to free help (if you want any that is). If you took a minute to look at the reply I made on your original issue you'll see my answer regarding Firefox.

If you want further help I expect you to not insult people, especially not me since you're highly unlikely to get a response from anyone else.
