### ISSUE TITLE
Error when changing landing page

### ISSUE THREAD

**Issue by Drarig29** [ActivityWatch/aw-webui#297] opened 2021-06-28 20:12 UTC
I have three options in the menu:

- Home
- Activity (msi)
- Activity (unknown)
- Timeline

Every option throws the same error:

```
TypeError: Cannot read property 'value' of undefined
    at change (LandingPageSettings.vue?f8a9:1)
    at ne (vue.runtime.esm.js:1854)
    at a.n (vue.runtime.esm.js:2179)
    at ne (vue.runtime.esm.js:1854)
    at a.Cn.t.$emit (vue.runtime.esm.js:3888)
    at a.<anonymous> (form-select.js:83)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at ce (vue.runtime.esm.js:1906)
```

**Comment by ErikBjare** [comment] 2021-07-01 12:30
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/611, closing.

**Closed by ErikBjare** 2021-07-01 12:30 UTC
